apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 808939434884.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:e70a4c72978229f77a9c3786e395a7b68e1c138d
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: earphones-service
  labels:
    app: earphones
spec:
  type: ClusterIP
  selector:
    app: earphones
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
